FROM maven AS build
COPY src /usr/app/src
COPY pom.xml /usr/app
WORKDIR /usr/app
RUN mvn clean package -DskipTests

FROM openjdk:8-jdk-alpine
WORKDIR /usr/app
COPY --from=build /usr/app/target/*.jar application.jar

ENTRYPOINT ["java", "-jar", "application.jar"]